import { readFileSync } from 'node:fs';
import { describe, expect, it } from 'vitest';
import { EXTRA_RULES, redirectRules, renderRedirects } from '../../scripts/redirects.mjs';
import { parseUrlMap } from './url-map';

const ROWS: Array<[string, string]> = [
  ['/a/', '/nou/a/'],
  ['/same/', '/same/'],
  ['/wp-content/uploads/2025/06/x.pdf', '/documente/x.pdf'],
];

describe('the redirect rules', () => {
  it('skips a row whose two paths are equal', () => {
    expect(redirectRules(ROWS).some((r) => r.from === '/same/')).toBe(false);
  });

  it('keeps every specific rule ABOVE the /wp-content/* 410', () => {
    const rules = redirectRules(ROWS);
    const upload = rules.findIndex((r) => r.from === '/wp-content/uploads/2025/06/x.pdf');
    const wildcard = rules.findIndex((r) => r.from === '/wp-content/*');
    expect(upload).toBeGreaterThanOrEqual(0);
    expect(wildcard).toBeGreaterThan(upload);
    expect(rules[wildcard].status).toBe(410);
  });

  it('puts every 410 after every 301', () => {
    const rules = redirectRules(ROWS);
    const last301 = rules.map((r) => r.status).lastIndexOf(301);
    const first410 = rules.map((r) => r.status).indexOf(410);
    expect(first410).toBeGreaterThan(last301);
  });

  it('refuses two rules for one old path', () => {
    expect(() => redirectRules([...ROWS, ['/a/', '/altrove/']])).toThrow(/two rules for \/a\//);
  });

  it('carries only 301 and 410', () => {
    for (const rule of redirectRules(ROWS)) expect([301, 410]).toContain(rule.status);
  });

  it('renders one line per rule, `from to status`, with a generated header', () => {
    const text = renderRedirects(redirectRules([['/a/', '/nou/a/']]));
    expect(text).toContain('/a/ /nou/a/ 301');
    expect(text.startsWith('# Generated by scripts/redirects.mjs')).toBe(true);
    expect(text.endsWith('\n')).toBe(true);
  });

  it('maps the old album, the calendar URLs and the apex', () => {
    const froms = EXTRA_RULES.map(([from]) => from);
    expect(froms).toContain('/galerie.html');
    expect(froms).toContain('/event/*');
    expect(froms).toContain('/events/*');
    expect(froms).toContain('https://bor-zh.ch/*');
  });

  it('holds over the real map: every non-equal row becomes one 301, none duplicated', () => {
    /*
     * NO PINNED ROW COUNT. Task 4 regenerates this CSV with eight more rows,
     * so a hard `144` here would go red in the middle of the plan for a reason
     * that is not a defect. The property is "every row that is not already
     * served becomes exactly one rule", computed from the file.
     */
    const rows = parseUrlMap(readFileSync('docs/url-map.csv', 'utf8'));
    expect(rows.length).toBeGreaterThanOrEqual(144);
    const rules = redirectRules(rows);
    const expected = rows.filter(([from, to]) => from !== to);
    expect(rules.filter((r) => r.status === 301 && rows.some(([f]) => f === r.from))).toHaveLength(
      expected.length,
    );
    expect(new Set(rules.map((r) => r.from)).size).toBe(rules.length);
    expect(rules.length).toBeLessThan(2000);
  });
});