/*
 * `/` — and only `/` — so the `?p=<id>` short links land on their new pages.
 *
 * A Pages Function file at `functions/index.ts` is routed to the root path
 * alone, which is exactly the surface these URLs use; `/api/contact` is
 * untouched, and every other path continues to the static asset as if this
 * file did not exist (`next()`).
 *
 * THE MAP IS A COMMITTED JSON FILE, generated by `migration/wp-ids.mjs` from
 * the dump and imported here. An id the map does not carry falls through to
 * the homepage: a stale short link lands on the parish's front page, which is
 * a better answer than a 404 and is what happens without this file at all.
 */
import { shortLinkTarget } from '../src/lib/short-links';
import WP_IDS from './wp-ids.json';

export const onRequest = async ({
  request,
  next,
}: {
  request: Request;
  next: () => Promise<Response>;
}): Promise<Response> => {
  if (request.method !== 'GET' && request.method !== 'HEAD') return next();
  const target = shortLinkTarget(new URL(request.url).searchParams.get('p'), WP_IDS);
  if (target === null) return next();
  return Response.redirect(new URL(target, request.url).toString(), 301);
};
