/*
 * The `_redirects` file, generated from `docs/url-map.csv` at `astro:build:done`.
 *
 * WHY GENERATED RATHER THAN COMMITTED. The CSV is the migration's output and
 * the single record of every old URL that keeps working; a committed
 * `public/_redirects` would be a second copy that drifts, and the drift is
 * invisible — Cloudflare never serves the file, so no test that reads the
 * deployed site can see which rules shipped. The integration reads the CSV at
 * build time, so the file and its input cannot disagree.
 *
 * THE ORDER IS THE FILE'S CONTENT, NOT A FORMATTING CHOICE. Cloudflare applies
 * the first matching rule, so the 18 specific `/wp-content/uploads/…` 301s
 * must sit ABOVE the `/wp-content/*` 410 or the wildcard shadows every one of
 * them and the PDFs behind them stop resolving. Every 301 therefore precedes
 * every 410, and the tests pin it by line index.
 *
 * THE 410s ARE AN INTENT THE PLATFORM DOES NOT DOCUMENT. Cloudflare's
 * `_redirects` reference lists 301, 302, 303, 307 and 308 as supported and
 * marks other status codes unsupported, so these four rules may not produce a
 * 410 on the deployed site. They stay because spec §12's intent is right and
 * the live behaviour is unmeasured; handover F5 records what actually comes
 * back, and a Pages Function or a Cloudflare rule is the deferred fallback.
 *
 * WHAT THE FILE CANNOT DO, named: `_redirects` matches paths, not query
 * strings, so the WordPress `?p=<id>` short links are the Task 3 Pages
 * Function's job (functions/index.ts, written without backticks until it
 * exists), and the 2,000-rule free-tier limit is far away at this size.
 */
import { readFileSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { parseUrlMap } from '../src/lib/url-map.ts';

/** The CSV, relative to the directory the build runs in. */
export const URL_MAP = 'docs/url-map.csv';

/** Rules that are not CSV rows: the old album page and the calendar URLs. */
export const EXTRA_RULES = [
  ['/galerie.html', '/galerie/', 301],
  ['/event/*', '/evenimente/', 301],
  ['/events/*', '/evenimente/', 301],
  ['https://bor-zh.ch/*', 'https://www.bor-zh.ch/:splat', 301],
];

/**
 * Spec §12's deliberate 410s. Bots probe these for years; 410 tells them to
 * stop. The destination is ignored for a 410 but the field must be present.
 */
export const GONE_RULES = [
  ['/wp-admin/*', '/', 410],
  ['/wp-login.php', '/', 410],
  ['/xmlrpc.php', '/', 410],
  ['/wp-content/*', '/', 410],
];

/**
 * The rules, in order. `rows` is the CSV's `[old, new]` pairs; `extras` and
 * `gone` are parameters so the unit tests can show the ordering without the
 * real tables, and default to the real ones.
 */
export function redirectRules(rows, extras = EXTRA_RULES, gone = GONE_RULES) {
  const rules = [];
  const seen = new Set();
  const push = ([from, to, status]) => {
    if (from === to) return;
    if (seen.has(from)) throw new Error(`two rules for ${from}`);
    seen.add(from);
    rules.push({ from, to, status });
  };
  for (const [from, to] of rows) push([from, to, 301]);
  for (const rule of extras) push(rule);
  for (const rule of gone) push(rule);
  return rules;
}

/** The file's text: a generated header, then one rule per line. */
export function renderRedirects(rules) {
  return (
    [
      '# Generated by scripts/redirects.mjs from docs/url-map.csv at astro:build:done.',
      '# Do not edit dist/_redirects by hand: edit the CSV, or the rule tables in the script.',
      ...rules.map(({ from, to, status }) => `${from} ${to} ${status}`),
    ].join('\n') + '\n'
  );
}

/**
 * Reads the CSV, writes `<dir>/_redirects`, and returns the rules. Prints what
 * it measured — the three classes of rule, not only the total — so a later
 * reader can tell which part changed.
 */
export function writeRedirects(dir, log = console.log) {
  const rows = parseUrlMap(readFileSync(join(process.cwd(), URL_MAP), 'utf8'));
  const rules = redirectRules(rows);
  writeFileSync(join(dir, '_redirects'), renderRedirects(rules));
  const fromMap = rules.filter((r) => r.status === 301 && rows.some(([f]) => f === r.from)).length;
  const extras = rules.filter((r) => r.status === 301 && !rows.some(([f]) => f === r.from)).length;
  const gone = rules.filter((r) => r.status === 410).length;
  log(`redirects: ${rules.length} rule(s) — ${fromMap} from the map, ${extras} extra, ${gone} gone`);
  return rules;
}

/** The Astro integration. Wired in `astro.config.mjs`. */
export const redirects = {
  name: 'redirects',
  hooks: {
    'astro:build:done': ({ dir, logger }) => {
      writeRedirects(fileURLToPath(dir), (message) => logger.info(message));
    },
  },
};
